# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import credential_pb2 as credential__pb2


class OauthCredentialStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveCredentials = channel.unary_unary(
                '/vietsoccer.firestore.api.OauthCredential/SaveCredentials',
                request_serializer=credential__pb2.Credential.SerializeToString,
                response_deserializer=credential__pb2.SaveCredentialResponse.FromString,
                )


class OauthCredentialServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SaveCredentials(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OauthCredentialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveCredentials,
                    request_deserializer=credential__pb2.Credential.FromString,
                    response_serializer=credential__pb2.SaveCredentialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vietsoccer.firestore.api.OauthCredential', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OauthCredential(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vietsoccer.firestore.api.OauthCredential/SaveCredentials',
            credential__pb2.Credential.SerializeToString,
            credential__pb2.SaveCredentialResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
