# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: credential.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='credential.proto',
  package='vietsoccer.firestore.api',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x63redential.proto\x12\x18vietsoccer.firestore.api\x1a\x1cgoogle/api/annotations.proto\"\x7f\n\nCredential\x12\r\n\x05token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x11\n\ttoken_uri\x18\x03 \x01(\t\x12\x11\n\tclient_id\x18\x04 \x01(\t\x12\x15\n\rclient_secret\x18\x05 \x01(\t\x12\x0e\n\x06scopes\x18\x06 \x03(\t\")\n\x16SaveCredentialResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9b\x01\n\x0fOauthCredential\x12\x87\x01\n\x0fSaveCredentials\x12$.vietsoccer.firestore.api.Credential\x1a\x30.vietsoccer.firestore.api.SaveCredentialResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\"\x0e/v1/credential:\x04\x64\x61tab\x06proto3'
  ,
  dependencies=[google_dot_api_dot_annotations__pb2.DESCRIPTOR,])




_CREDENTIAL = _descriptor.Descriptor(
  name='Credential',
  full_name='vietsoccer.firestore.api.Credential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='vietsoccer.firestore.api.Credential.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='refresh_token', full_name='vietsoccer.firestore.api.Credential.refresh_token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token_uri', full_name='vietsoccer.firestore.api.Credential.token_uri', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_id', full_name='vietsoccer.firestore.api.Credential.client_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_secret', full_name='vietsoccer.firestore.api.Credential.client_secret', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scopes', full_name='vietsoccer.firestore.api.Credential.scopes', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=203,
)


_SAVECREDENTIALRESPONSE = _descriptor.Descriptor(
  name='SaveCredentialResponse',
  full_name='vietsoccer.firestore.api.SaveCredentialResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='vietsoccer.firestore.api.SaveCredentialResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=246,
)

DESCRIPTOR.message_types_by_name['Credential'] = _CREDENTIAL
DESCRIPTOR.message_types_by_name['SaveCredentialResponse'] = _SAVECREDENTIALRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Credential = _reflection.GeneratedProtocolMessageType('Credential', (_message.Message,), {
  'DESCRIPTOR' : _CREDENTIAL,
  '__module__' : 'credential_pb2'
  # @@protoc_insertion_point(class_scope:vietsoccer.firestore.api.Credential)
  })
_sym_db.RegisterMessage(Credential)

SaveCredentialResponse = _reflection.GeneratedProtocolMessageType('SaveCredentialResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAVECREDENTIALRESPONSE,
  '__module__' : 'credential_pb2'
  # @@protoc_insertion_point(class_scope:vietsoccer.firestore.api.SaveCredentialResponse)
  })
_sym_db.RegisterMessage(SaveCredentialResponse)



_OAUTHCREDENTIAL = _descriptor.ServiceDescriptor(
  name='OauthCredential',
  full_name='vietsoccer.firestore.api.OauthCredential',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=249,
  serialized_end=404,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaveCredentials',
    full_name='vietsoccer.firestore.api.OauthCredential.SaveCredentials',
    index=0,
    containing_service=None,
    input_type=_CREDENTIAL,
    output_type=_SAVECREDENTIALRESPONSE,
    serialized_options=b'\202\323\344\223\002\026\"\016/v1/credential:\004data',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OAUTHCREDENTIAL)

DESCRIPTOR.services_by_name['OauthCredential'] = _OAUTHCREDENTIAL

# @@protoc_insertion_point(module_scope)
